const EMAIL_USER = process.env.EMAIL_USER;
const EMAIL_PASS = process.env.EMAIL_PASS;
const NEXT_PUBLIC_RECAPTCHA_SITE_KEY = process.env.NEXT_PUBLIC_RECAPTCHA_SITE_KEY;
const RECAPTCHA_SECRET_KEY = process.env.RECAPTCHA_SECRET_KEY;
const MONGODB_URI = process.env.MONGODB_URI;
const DB_NAME = 'mzeeshankhan';
export {
  EMAIL_USER,
  EMAIL_PASS,
  NEXT_PUBLIC_RECAPTCHA_SITE_KEY,
  RECAPTCHA_SECRET_KEY,
  MONGODB_URI,
  DB_NAME,
};
